### ISSUE TITLE
Send key to windows when hiding it

### ISSUE THREAD

**Issue by microyea** [IvanHanloth/Boss-Key#2]
请增加一个配置：在隐藏窗口之前发送按键给窗口。 使用场景：暂停视频的播放

**Comment by IvanHanloth** [comment]
我会尝试在新版本中添加该配置，但是发送热键并不总能实现视频暂停

**Comment by microyea** [comment]
大部分视频软件可以用空格键暂停， 可以用抖音测试 :)

**Comment by IvanHanloth** [comment]
我最近在测试此功能。我发现如果需要通过发送热键暂停视频的话，必须要添加一定的等待时间才能实现，这可能会导致窗口无法及时隐藏

**Comment by microyea** [comment]
可否向隐藏窗口发热键？

**Comment by IvanHanloth** [comment]
如果通过模拟按键的形式，可能不行。我会尝试通过系统api的形式发送键盘按键消息

**Comment by IvanHanloth** [comment]
SendBeforeHide分支已经基本实现此功能，但是还存在以下问题：

- 窗口隐藏会被延迟0.25秒

在合并前仍需解决的问题有：

- 目前只支持space按键，窗口中设置的“隐藏前发送的热键”配置无效（此配置的存在还需考量）
